
sql_template = dict(
  log_session_run=None,  # get log of folder-workflow-session ran ordered by most recent
  list_source=None,  # get list of unique sources
  list_target=None,  # get list of unique targets
  list_transformation=None,  # get list of unique transformations
  list_instance=None,  # get list of unique instances in each mapping
  list_mapping=None,  # get list of unique mappings
  list_mapplet=None,  # get list of unique mapplets
  list_session=None,  # get list of unique mappings
  list_source_fields=None, # get list of fields for a source
  list_target_fields=None, # get list of fields for a source
)

sql_oracle = dict(
log_session_run = ''' -- Also see INF_RP.OPB_WFLOW_RUN
SELECT
  "ABSOLUTEFILENAME", -- binary log path
  "NODENAME",
  "INTEGRATIONSERVICE",
  "REPOSITORYDOMAIN",
  "REPOSITORYNAME",
  "RUNCONTEXT",  -- folder_id, workflow_id, session_id
  "RUNID", -- workflow_run_id, ?, ?
  "ENTRYTIME", -- starttime in milli-epoch -> datetime.datetime.fromtimestamp(1473705355958/1000.0)
  "FOLDER", -- folder text
  "WORKFLOW", -- workflow text
  "SESSIONPATH", -- session text
  "OSUSER",
  "RUNINSTANCENAME"
FROM
  "INF_DD"."ISP_RUN_LOG"
WHERE 1=1
AND ROWNUM <= {limit}
ORDER BY ENTRYTIME desc
''',

list_mapping='''
SELECT
  "PARENT_SUBJECT_AREA",
  "PARENT_SUBJECT_ID",
  "SUBJECT_AREA",
  "SUBJECT_ID", -- folder_id
  "PARENT_MAPPING_NAME",
  "PARENT_MAPPING_ID",
  "PARENT_MAPPING_VERSION_NUMBER",
  "PARENT_MAPPING_VERSION_STATUS",
  "PARENT_MAPPING_UTC_CHECKIN",
  "PARENT_MAPPING_UTC_LAST_SAVED",
  "PARENT_MAPPING_LAST_SAVED",
  "PARENT_MAPPING_IS_VALID",
  "PARENT_MAPPING_DESCRIPTION",
  "MAPPING_NAME", -- mapping_name
  "MAPPING_ID", -- mapping_id
  "MAPPING_VERSION_NUMBER",
  "MAPPING_VERSION_STATUS",
  "MAPPING_UTC_CHECKIN",
  "MAPPING_UTC_LAST_SAVED", -- starttime in epoch -> datetime.datetime.fromtimestamp(1473705355958)
  "MAPPING_LAST_SAVED",
  "MAPPING_DESCRIPTION",
  "REPOSITORY_NAME",
  "IS_GLOBAL_SHORTCUT",
  "IS_SHORTCUT"
FROM
  "INF_RP"."REP_ALL_MAPPINGS"
WHERE 1=1
AND SUBJECT_ID = {folder_id}
''',

list_mapplet='''
SELECT
  "PARENT_SUBJECT_AREA",
  "PARENT_SUBJECT_ID",
  "SUBJECT_AREA",
  "SUBJECT_ID", -- folder_id
  "PARENT_MAPPLET_NAME",
  "PARENT_MAPPLET_ID",
  "PARENT_MAPPLET_VERSION_NUMBER",
  "PARENT_MAPPLET_VERSION_STATUS",
  "PARENT_MAPPLET_UTC_CHECKIN",
  "PARENT_MAPPLET_UTC_LAST_SAVED",
  "PARENT_MAPPLET_LAST_SAVED",
  "PARENT_MAPPLET_IS_VALID",
  "PARENT_MAPPLET_DESCRIPTION",
  "MAPPLET_NAME", -- mapplet_name
  "MAPPLET_ID", -- mapplet_id
  "MAPPLET_VERSION_NUMBER",
  "MAPPLET_VERSION_STATUS",
  "MAPPLET_UTC_CHECKIN",
  "MAPPLET_UTC_LAST_SAVED",
  "MAPPLET_LAST_SAVED",
  "MAPPLET_DESCRIPTION",
  "REF_WIDGET_ID",
  "REPOSITORY_NAME",
  "IS_GLOBAL_SHORTCUT",
  "IS_SHORTCUT"
FROM
  "INF_RP"."REP_ALL_MAPPLETS"
WHERE 1=1
AND SUBJECT_ID = {folder_id}
''',

list_workflow='''
SELECT
  "SUBJECT_AREA",
  "WORKFLOW_NAME",
  "SCHEDULER_NAME",
  "START_TIME",
  "END_TIME",
  "IS_RUN_ON_LIMIT",
  "RUN_OPTIONS",
  "END_OPTIONS",
  "DELTA_VALUE",
  "RUN_COUNT",
  "SCHEDULER_ID",
  "SCHEDULER_IS_REUSABLE",
  "SCHEDULER_COMMENTS",
  "SCHEDULER_VERSION_NUMBER",
  "WORKFLOW_VERSION_NUMBER",
  "WORKFLOW_ID", -- workflow_id
  "WORKFLOW_IS_VALID",
  "WORKFLOW_IS_SERVICE",
  "WORKFLOW_IS_RUNNABLE_SERVICE",
  "WORKFLOW_LAST_SAVED",
  "WORKFLOW_COMMENTS",
  "SUBJECT_ID", -- folder_id
  "SERVER_NAME",
  "SERVER_ID",
  "WORKFLOW_IS_IMPACTED"
FROM
  "INF_RP"."REP_WORKFLOWS"
WHERE 1=1
AND SUBJECT_ID = {folder_id}  
'''

list_source='''
SELECT
  "PARENT_SUBJECT_AREA",
  "PARENT_SUBJECT_ID",
  "PARENT_SOURCE_NAME",
  "PARENT_SOURCE_BUSINESS_NAME",
  "PARENT_SOURCE_ID",
  "PARENT_SOURCE_DESCRIPTION",
  "PARENT_SOURCE_VERSION_NUMBER",
  "PARENT_SOURCE_VERSION_STATUS",
  "PARENT_SOURCE_UTC_CHECKIN",
  "PARENT_SOURCE_UTC_LAST_SAVED",
  "PARENT_SOURCE_LAST_SAVED",
  "PARENT_SOURCE_SCHEMA_NAME",
  "PARENT_SOURCE_FIRST_FIELD_ID",
  "PARENT_SOURCE_SELECT_INFO_ID",
  "PARENT_SOURCE_DISPLAY_SIZE",
  "PARENT_SOURCE_PHYSICAL_SIZE",
  "PARENT_SRC_MIN_PHYSICAL_SIZE",
  "PARENT_SOURCE_DATABASE_NAME",
  "PARENT_SOURCE_TYPE",
  "PARENT_SOURCE_DATABASE_TYPE",
  "SUBJECT_AREA",
  "SUBJECT_ID",  -- folder_id
  "SOURCE_NAME",  -- source name
  "SOURCE_ID",  -- source_id
  "SOURCE_DESCRIPTION",
  "SOURCE_VERSION_NUMBER",
  "SOURCE_VERSION_STATUS",
  "SOURCE_UTC_CHECKIN",
  "SOURCE_UTC_LAST_SAVED", -- starttime in epoch -> datetime.datetime.fromtimestamp(1473705355958)
  "SOURCE_LAST_SAVED",
  "SOURCE_DATABASE_NAME", -- database_name
  "REPOSITORY_NAME",
  "IS_SHORTCUT",
  "IS_GLOBAL_SHORTCUT",
  OPB_SRC.OWNERNAME
FROM
  "INF_RP"."REP_ALL_SOURCES", "INF_RP"."OPB_SRC"
WHERE 1=1
AND REP_ALL_SOURCES.SOURCE_ID = OPB_SRC.SRC_ID
AND SUBJECT_ID = {folder_id}
'''

list_source_fields='''
SELECT
  "PARENT_SUBJECT_AREA",
  "PARENT_SUBJECT_ID",
  "PARENT_SOURCE_NAME",
  "PARENT_SOURCE_BUSINESS_NAME",
  "PARENT_SOURCE_ID",
  "PARENT_SOURCE_DESCRIPTION",
  "PARENT_SOURCE_VERSION_NUMBER",
  "PARENT_SOURCE_VERSION_STATUS",
  "PARENT_SOURCE_UTC_CHECKIN",
  "PARENT_SOURCE_UTC_LAST_SAVED",
  "PARENT_SOURCE_LAST_SAVED",
  "PARENT_SOURCE_TYPE",
  "PARENT_SOURCE_DATABASE_NAME",
  "PARENT_SOURCE_DATABASE_TYPE",
  "SUBJECT_AREA",
  "SUBJECT_ID",
  "SOURCE_NAME",
  "SOURCE_ID",
  "SOURCE_DESCRIPTION",
  "SOURCE_VERSION_NUMBER",
  "SOURCE_VERSION_STATUS",
  "SOURCE_UTC_CHECKIN",
  "SOURCE_UTC_LAST_SAVED",
  "SOURCE_LAST_SAVED",
  "SOURCE_DATABASE_NAME",
  "SOURCE_FIELD_NAME",
  "SOURCE_FIELD_BUSINESS_NAME",
  "SOURCE_FIELD_ID",
  "SOURCE_FIELD_DESCRIPTION",
  "SOURCE_FIELD_NUMBER",
  "SOURCE_FIELD_NEXT_FIELD_ID",
  "SOURCE_FIELD_LEVEL",
  "SOURCE_FIELD_PICTURE_TEXT",
  "SOURCE_FIELD_OCCURS_TIMES",
  "SOURCE_FIELD_REDEFINES_FIELD",
  "SOURCE_FIELD_DISPLAY_OFFSET",
  "SOURCE_FIELD_DISPLAY_LENGTH",
  "SOURCE_FIELD_PHYSICAL_OFFSET",
  "SOURCE_FIELD_PHYSICAL_LENGTH",
  "SOURCE_FIELD_CHILD_FIELD_ID",
  "SOURCE_FIELD_KEY_TYPE",
  "SOURCE_FIELD_DATATYPE",
  "SOURCE_FIELD_PRECISION",
  "SOURCE_FIELD_SCALE",
  "SOURCE_FIELD_PIC_USAGE_NAME",
  "SOURCE_FIELD_NULLTYPE",
  "REPOSITORY_NAME",
  "IS_SHORTCUT",
  "IS_GLOBAL_SHORTCUT"
FROM
  "INF_RP"."REP_ALL_SOURCE_FLDS"
WHERE 1=1
AND SUBJECT_ID = {folder_id}
AND SOURCE_ID = {source_id}
'''

list_target_fields='''
SELECT
  "PARENT_SUBJECT_AREA",
  "PARENT_SUBJECT_ID",
  "PARENT_TARGET_NAME",
  "PARENT_TARGET_BUSINESS_NAME",
  "PARENT_TARGET_ID",
  "PARENT_TARGET_DESCRIPTION",
  "PARENT_TARGET_VERSION_NUMBER",
  "PARENT_TARGET_VERSION_STATUS",
  "PARENT_TARGET_UTC_CHECKIN",
  "PARENT_TARGET_UTC_LAST_SAVED",
  "PARENT_TARGET_LAST_SAVED",
  "PARENT_TARGET_FILE_ID",
  "PARENT_TARGET_DATABASE_TYPE",
  "SUBJECT_AREA",
  "SUBJECT_ID",
  "TARGET_NAME",
  "TARGET_ID",
  "TARGET_DESCRIPTION",
  "TARGET_VERSION_NUMBER",
  "TARGET_VERSION_STATUS",
  "TARGET_UTC_CHECKIN",
  "TARGET_UTC_LAST_SAVED",
  "TARGET_LAST_SAVED",
  "TARGET_FIELD_NAME",
  "TARGET_FIELD_BUSINESS_NAME",
  "TARGET_FIELD_ID",
  "TARGET_FIELD_DESCRIPTION",
  "TARGET_FIELD_NUMBER",
  "TARGET_FIELD_NEXT_FIELD_ID",
  "TARGET_FIELD_PICTURE_TEXT",
  "TARGET_FIELD_IS_NULLABLE",
  "TARGET_FIELD_SOURCE_FIELD_ID",
  "TARGET_FIELD_KEY_TYPE",
  "TARGET_FIELD_DATATYPE",
  "TARGET_FIELD_DATATYPE_GROUP",
  "TARGET_FIELD_PRECISION",
  "TARGET_FIELD_SCALE",
  "REPOSITORY_NAME",
  "IS_SHORTCUT",
  "IS_GLOBAL_SHORTCUT"
FROM
  "INF_RP"."REP_ALL_TARGET_FLDS"
WHERE 1=1
AND SUBJECT_ID = {folder_id}
AND TARGET_ID = {target_id}
'''

list_target='''
SELECT
  "PARENT_SUBJECT_AREA",
  "PARENT_SUBJECT_ID",
  "PARENT_TARGET_NAME",
  "PARENT_TARGET_BUSINESS_NAME",
  "PARENT_TARGET_ID",
  "PARENT_TARGET_DESCRIPTION",
  "PARENT_TARGET_VERSION_NUMBER",
  "PARENT_TARGET_VERSION_STATUS",
  "PARENT_TARGET_UTC_CHECKIN",
  "PARENT_TARGET_UTC_LAST_SAVED",
  "PARENT_TARGET_LAST_SAVED",
  "PARENT_TARGET_FIRST_FIELD_ID",
  "PARENT_TARGET_CONSTRAINT",
  "PARENT_TARGET_CREATE_OPTIONS",
  "PARENT_TARGET_FIRST_INDEX_ID",
  "PARENT_TARGET_FILE_ID",
  "PARENT_TARGET_DATABASE_TYPE",
  "SUBJECT_AREA",
  "SUBJECT_ID", -- folder_id
  "TARGET_NAME", -- target_name
  "TARGET_ID", -- target_id
  "TARGET_DESCRIPTION",
  "TARGET_VERSION_NUMBER",
  "TARGET_VERSION_STATUS",
  "TARGET_UTC_CHECKIN",
  "TARGET_UTC_LAST_SAVED", -- starttime in epoch -> datetime.datetime.fromtimestamp(1473705355958)
  "TARGET_LAST_SAVED",
  "REPOSITORY_NAME",
  "IS_SHORTCUT",
  "IS_GLOBAL_SHORTCUT"
FROM
  "INF_RP"."REP_ALL_TARGETS"
WHERE 1=1
AND SUBJ_ID = {folder_id}
'''

list_transformation='''
SELECT
  "WIDGET_NAME",  -- transf_name
  "WIDGET_ID", -- transf_id
  "WIDGET_TYPE", -- trans_type
  "IS_REUSABLE",
  "SUBJECT_ID", -- folder_id
  "VERSION_ID",
  "COMMENTS",
  "WIDGET_PROP",
  "LAST_SAVED",
  "CREATE_INFO",
  "OBJVERSION",
  "VERSION_NUMBER",
  "VERSION_STATUS",
  "UTC_LAST_SAVED",
  "IS_VISIBLE",
  "CHECKOUT_USER_ID",
  "IS_MARKED",
  "UTC_REF_TIME",
  "UTC_CHECKIN",
  "TEMPLATE_ID",
  "RU_PARENT_ID",
  "RU_VERSION_NUMBER",
  "OBJ_CMP",
  "FILE_ID",
  "COMP_VERSION"
FROM
  "INF_RP"."OPB_WIDGET"
WHERE 1=1
AND SUBJECT_ID = {folder_id}
'''

list_instance='''
SELECT
  "MAPPING_ID", -- mapping_id
  "WIDGET_ID", -- transf_id
  "WIDGET_TYPE", -- trans_type
  "INSTANCE_ID", -- instance_id
  "INSTANCE_NAME", -- instance_name
  "COMMENTS",
  "WIDGET_PROP",
  "VERSION_NUMBER",
  "REF_VERSION_NUMBER"
FROM
  "INF_RP"."OPB_WIDGET_INST"
WHERE 1=1
AND MAPPING_ID = {mapping_id}
'''

list_session='''
SELECT
  "SUBJECT_AREA",
  "SUBJECT_ID",
  "TASK_NAME",
  "TASK_ID",
  "IS_VALID",
  "LAST_SAVED",
  "DESCRIPTION",
  "VERSION_NUMBER",
  "IS_ENABLED",
  "UTC_CHECKIN",
  "UTC_LAST_SAVED",
  "IS_REUSABLE",
  "TASK_TYPE",
  "TASK_TYPE_NAME"
FROM
  "INF_RP"."REP_ALL_TASKS"
WHERE TASK_TYPE = 68
AND SUBJECT_ID = {folder_id}
'''

)